[package]
name = "static_generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex="1.10"
walkdir = "2"
dotenv = "0.15.0"
chrono = "0.4"


